/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WowMarket;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class App extends Application {
    static final String JDBC_DRIVER = "org.postgresql.Driver";
    static final String DB_URL = "jdbc:postgresql://localhost/postgres";

    static final String USER = "postgres";
    static final String PASS = "";

    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        Connection conn = null;
        Statement stmt = null;
        try {
            Class.forName(JDBC_DRIVER);
            
            System.out.println("Connection to database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);

        //     System.out.println("Creating table in given database...");
        //     stmt = conn.createStatement();
        //     String sql = "CREATE TABLE REGISTRATION " +
        //         "(id INTEGER not NULL, " +
        //         " first VARCHAR(255), " +
        //         " last VARCHAR(255), " +
        //         " age INTEGER, " +
        //         " PRIMARY KEY ( id ))";
        //     stmt.executeUpdate(sql);
        //     System.out.println("Created table in given database...");

        //     stmt.close();
        //     conn.close();
        } catch (SQLException se) {
            se.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (stmt != null) stmt.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
        System.out.println("Goodbye!");
        launch();
    }
}
