/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WowMarket;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.net.URL;
import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        try {
            FXMLLoader loader = new FXMLLoader();
            URL url = getClass().getResource("/MainScene.fxml");
            loader.setLocation(url);
            Parent pane = loader.load();
            Scene scene = new Scene(pane, 640, 480);
            stage.setScene(scene);
            stage.setTitle("WowMarket");
            stage.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        /*WowDB wowDB = new WowDB();
        try {
            wowDB.connect("area_52", "postgres", "XXBankai00");
            List<Map<String, Object>> price_list = wowDB.getItem(153050);
            for (Map<String, Object> mp : price_list) {
                System.out.println("{");
                for (Map.Entry<String, Object> entry : mp.entrySet()) {
                    System.out.print(entry.getKey() + " : ");
                    if (entry.getValue() instanceof Timestamp) {
                        System.out.println(entry.getValue());
                    }
                    else if (entry.getValue() instanceof Integer) {
                        System.out.println(entry.getValue());
                    }
                    else if (entry.getValue() instanceof Long) {
                        System.out.println(entry.getValue());
                    }
                    else {
                        throw new IllegalStateException("Bad state");
                    }
                }
                System.out.println("}");
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(0);
        }
        */
        launch();
    }
}
